export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
export const REFRESH_SUBREDDIT = 'REFRESH_SUBREDDIT';
export const LOAD_MORE_POSTS = 'LOAD_MORE_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
